/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BlockUI: typeof import('primevue/blockui')['default']
    BottomInfo: typeof import('./src/components/BottomInfo.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    CodeReviewsPanel: typeof import('./src/components/UserCard/CodeReviewsPanel.vue')['default']
    CommitsPanel: typeof import('./src/components/UserCard/CommitsPanel.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IssuesPanel: typeof import('./src/components/UserCard/IssuesPanel.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuBar: typeof import('primevue/menubar')['default']
    Overview: typeof import('./src/components/UserCard/Overview.vue')['default']
    OverviewPanel: typeof import('./src/components/UserCard/OverviewPanel.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    PullRequestsPanel: typeof import('./src/components/UserCard/PullRequestsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
